apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  generation: 3
  labels:
    argocd.argoproj.io/instance: notification-automation
  name: notifications-wildcard-route
  namespace: knative-serving
spec:
  http:
  - backends:
    - serviceName: kourier
      servicePort: 80
    match:
      hosts:
      - '*.na.develop.eoepca.org'
      - '*.default.na.develop.eoepca.org'
      - '*.knative-serving.na.develop.eoepca.org'
      paths:
      - /*
    name: knative-serving-default
  ingressClassName: apisix
