apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.16"
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      develop.eoepca.org: ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
